version: 1.1.{build}
image: Visual Studio 2019
configuration: Release
platform: x86
cache: c:\tools\vcpkg\installed\
install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install fluidsynth:x86-windows
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%
build:
  project: WinGridStrument.sln
  verbosity: normal
artifacts:
- path: Release/WinGridStrument.exe
  name: binary
- path: Release/libfluidsynth-2.dll
  name: binary
- path: Release/glib-2.dll
  name: binary
- path: Release/pcre.dll
  name: binary
- path: Release/libiconv.dll
  name: binary
- path: Release/libcharset.dll
  name: binary
- path: Release/libintl.dll
  name: binary